// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUdyj_T8W0RPyvQqTtZDLkhPI-jXGf7DU',
    appId: '1:796366819868:web:67d3ca7da589a2219f45d9',
    messagingSenderId: '796366819868',
    projectId: 'mobile-app-e112c',
    authDomain: 'mobile-app-e112c.firebaseapp.com',
    storageBucket: 'mobile-app-e112c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_HkFSJ8oUcAXl8SDTL2fBR78e84TQ03o',
    appId: '1:796366819868:android:6f7adb598c5530009f45d9',
    messagingSenderId: '796366819868',
    projectId: 'mobile-app-e112c',
    storageBucket: 'mobile-app-e112c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7mrBmGaGco1VYiuub1GNuL9XDVUUSCeg',
    appId: '1:796366819868:ios:f690f8f10e0871ae9f45d9',
    messagingSenderId: '796366819868',
    projectId: 'mobile-app-e112c',
    storageBucket: 'mobile-app-e112c.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7mrBmGaGco1VYiuub1GNuL9XDVUUSCeg',
    appId: '1:796366819868:ios:f690f8f10e0871ae9f45d9',
    messagingSenderId: '796366819868',
    projectId: 'mobile-app-e112c',
    storageBucket: 'mobile-app-e112c.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUdyj_T8W0RPyvQqTtZDLkhPI-jXGf7DU',
    appId: '1:796366819868:web:5a4798fc4122f00c9f45d9',
    messagingSenderId: '796366819868',
    projectId: 'mobile-app-e112c',
    authDomain: 'mobile-app-e112c.firebaseapp.com',
    storageBucket: 'mobile-app-e112c.firebasestorage.app',
  );
}
